### ISSUE TITLE
siptreadmill appears to run but no sip generated ...

### ISSUE THREAD

**Issue by pauls1024** [adhearsion/SIPtreadmill#39]
Hi,
I have installed siptreadmill from packages onto a new install Ubunty Trusty.  When I run a scenario it seems to complete, the error, statistics and summary output files are all created ... but they are all zero length.  If I run ngrep on the asterisk box under test there are no SIP packets coming from the siptreadmill.

My current theory is that the job is being queued but then immediately being killed by sidekiq... I have no idea how to test or debug any further!  Not sure if it has any bearing or not but I have installed Ubuntu and Siptreadmill in an LXC container environement.

In the worker log I see:
`2015-07-01T08:59:01Z 265 TID-os0mp7rt8 TestRunWorker JID-07b7e1c9cb3cebe8f7aa76eb INFO: start
Preparing to run SIPp command: sudo $(which sipp) -p 8838 -sf /tmp/scenario20150701-265-1lzrcj4 -l 1 -m 1 -r 1 -t u1 -inf /tmp/csv20150701-265-5zzaz3 10.210.2.60
Test completed successfully but some calls failed.
Preparing to run SIPp command: sudo $(which sipp) -p 8838 -sf /tmp/scenario20150701-265-7s65zi -t u1 -inf /tmp/csv20150701-265-1cm40rj 
Preparing to run SIPp command: sudo $(which sipp) -p 8836 -sf /tmp/scenario20150701-265-1vo2jqn -l 5 -m 10 -r 1 -s 00442800000000 -mp 27439 -trace_stat -stf /tmp/stats20150701-265-1hrc09e -fd 1 -trace_screen -screen_file /tmp/summary_report20150701-265-a0tznx -trace_err -error_file /tmp/errors_report20150701-265-1g7nnzc -t u1 -inf /tmp/csv20150701-265-2ysszk 10.210.2.60
Test completed successfully but some calls failed.
Statistics logged at /tmp/stats20150701-265-1hrc09e
Test completed successfully but some calls failed.
2015-07-01T08:59:01Z 265 TID-os0mp7rt8 TestRunWorker JID-07b7e1c9cb3cebe8f7aa76eb INFO: done: 0.15 sec`

If I run the same SIPP commands from the command line as siptreadmill user they generate SIP traffic.

If I do a "dpkg-reconfigure dash" and revert to bash I get a similar result, but different worker log:

```
2015-07-01T09:02:26Z 307 TID-ouqnpmjd8 TestRunWorker JID-885c4f7d42d2e368706b6fd8 INFO: start
Preparing to run SIPp command: sudo $(which sipp) -p 8838 -sf /tmp/scenario20150701-307-1innlkm -l 1 -m 1 -r 1 -t u1 -inf /tmp/csv20150701-307-1b9lkes 10.210.2.60
Test completed successfully but some calls failed.
Preparing to run SIPp command: sudo $(which sipp) -p 8838 -sf /tmp/scenario20150701-307-1dr3v4k -t u1 -inf /tmp/csv20150701-307-1ji8xa9 
Preparing to run SIPp command: sudo $(which sipp) -p 8836 -sf /tmp/scenario20150701-307-uqx7iy -l 5 -m 10 -r 1 -s 00442800000000 -mp 26886 -trace_stat -stf /tmp/stats20150701-307-12b1emp -fd 1 -trace_screen -screen_file /tmp/summary_report20150701-307-1f1i658 -trace_err -error_file /tmp/errors_report20150701-307-uzcpos -t u1 -inf /tmp/csv20150701-307-mu54td 10.210.2.60
Test completed successfully but some calls failed.
Statistics logged at /tmp/stats20150701-307-12b1emp
2015-07-01T09:02:26Z 307 TID-ouqnpmjd8 TestRunWorker JID-885c4f7d42d2e368706b6fd8 INFO: fail: 0.145 sec
2015-07-01T09:02:26Z 307 TID-ouqnpmjd8 WARN: {"retry"=>false, "queue"=>"default", "class"=>"TestRunWorker", "args"=>[77, nil], "jid"=>"885c4f7d42d2e368706b6fd8", "enqueued_at"=>1435741346.679472}
2015-07-01T09:02:26Z 307 TID-ouqnpmjd8 WARN: Operation not permitted
2015-07-01T09:02:26Z 307 TID-ouqnpmjd8 WARN: /opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sippy_cup-0.6.0/lib/sippy_cup/runner.rb:54:in `kill'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sippy_cup-0.6.0/lib/sippy_cup/runner.rb:54:in `stop'
/opt/siptreadmill/app/services/test_runner.rb:83:in `halt_receiver_scenario'
/opt/siptreadmill/app/services/test_runner.rb:36:in `run'
/opt/siptreadmill/app/workers/test_run_worker.rb:17:in `perform'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:48:in `block (3 levels) in process'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:115:in `call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:115:in `block in invoke'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:117:in `block in invoke'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:117:in `block in  nvoke'
▽opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/logging.rb:22:in `with_context'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:117:in `block in invoke'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:120:in `call'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/middleware/chain.rb:120:in `invoke'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:47:in `block (2 levels) in process'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:102:in `stats'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:46:in `block in process'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:83:in `do_defer'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/sidekiq-2.13.1/lib/sidekiq/processor.rb:37:in `process'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `public_send'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/calls.rb:25:in `dispatch'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/calls.rb:125:in `dispatch'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/actor.rb:326:in `block in handle_message'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/tasks.rb:42:in `block in initialize'
/opt/siptreadmill/vendor/bundle/ruby/2.2.0/gems/celluloid-0.14.1/lib/celluloid/tasks/task_fiber.rb:11:in `block in create'
** [Airbrake] Unable to contact the Airbrake server. HTTP Error=execution expired
** [Airbrake] Failure: NilClass
```

Any insight or advice would be appreciated
Thanks

**Comment by pauls1024** [comment]
Seems like it was an LXC or Ubuntu installation issue...
I have installed Ubuntu Trust LTS server on bare metal and then installed siptreadmill from packages... I can now see the generated SIP messages on my PBX and some results graphs on the siptreadmill GUI.

Next step is to build some valid scenarios to run useful tests.

**Comment by benlangfeld** [comment]
Glad you got this fixed @pauls1024!
